- App.js
- components/Home/home.jsx
- components/HomeRoutes/homeRoutes.jsx
- components/Investor/investor.jsx
- components/Wallet/wallet.jsx
- components/logIn.jsx
- package-lock.json
- response.js
Implemente los componentes Home, Investor y Wallet con sus respectivas carpetas, y ademas agregue un HomeRoutes para que quede mas limpio el codigo y solo renderizemos los componentes.
> (Home,Investor,Wallet) implementadas

- App.js
- src/components/RegisterB/registerB.jsx
- src/components/RegisterC/registerC.jsx
Cambio de estilo y nuevo componente Register C
> Register C y cambios de estilo

- App.js
- src/components/Home/home.jsx
- src/components/HomeRoutes/homeRoutes.jsx
- src/components/UserCardHome/userCardHome.jsx
- src/redux/actions/index.js
- src/redux/reducer/index.js
- src/redux/store/index.js
Arregle el Redux, Implemente un nuevo componente Card para el home... espero code review!
> Redux fixeado, Nuevo componente de Card User

- src/components/Login/logIn.jsx
- src/components/RegisterA/RegisterA.jsx
> Nuevos estilos

- src/components/Home/Home.jsx
- src/components/Wallet/Wallet.jsx
> Fix Styles2

- src/components/Home/Home.jsx
- src/components/Login/LogIn.jsx
- src/components/RegisterA/RegisterA.jsx
- src/components/Success/Success.jsx
- src/components/UserCardHome/UserCardHome.jsx
Arreglo de todos los bugs y warning en PC/Phone.
> Fix bug phone

- package.json
- src/components/RegisterA/RegisterA.jsx
- src/components/Wallet/Wallet.jsx
Se corrigio el inconveniente con el package.json y se termina el componente wallet
> componente wallet terminado y correccion con los paquetes

- src/components/CarouselImages/CarouselImages.jsx
- src/components/Wallet/Wallet.jsx
Estilos a carousel en componente Wallet
> carousel de wallet terminado

- src/components/UserCapital/UserCapital.jsx
- src/components/UserCardHome/UserCardHome.jsx
Arreglos en mobile, bugs visuales en componentes.
> Arreglos en mobile

- src/components/Investor/Investor.jsx
- src/components/Possession/Possession.jsx
- src/components/Wallet/Wallet.jsx
- src/components/WalletTotal/WalletTotal.jsx
Pantalla lista del componente investor
> Se agrego la primera pantalla en la pestaña investor/

- App.js
- src/components/CardCoinsInvestorBuy/CardCoinsInvestorBuy.jsx
- src/components/Investor/Investor.jsx
- src/components/InvestorBuy/InvestorBuy.jsx
Agregados dos componentes mas: CardCoins y InvestorBuy
> Incorporada una pantalla en el app y agregados dos componentes mas

- src/components/Home/Home.jsx
- src/components/HomeBubbleMenu/HomeBubbleMenu.jsx
Componente de menu burbuja incorporado y estructurado, tenemos que discutir sobre como hacer la funcionalidad.
> Componente de HomeBubbleMenu estructurado, falta funcionalidad.

- src/components/InvestorBuy/InvestorBuy.jsx
- src/components/Login/LogIn.jsx
- src/components/NavigationContainer/navigationContainer.jsx
- src/redux/actions/index.js
- src/redux/reducer/index.js
Agregue funcionalidad al componente login y maquete la futura conexión al back para el login.
> Log in validado

- App.js
- package.json
- src/components/CardCoinsInvestorBuy/CardCoinsInvestorBuy.jsx
- src/components/DetailCoinsInvestorBuy/DetailCoinsInvestorBuy.jsx
- src/components/InvestorBuy/InvestorBuy.jsx
Se soluciono el bug que habia con el teclado. **RECORDAR HACER NPM INSTALL UNA VEZ HECHO EL PULL**
> Agregado componente CoinsDetail y solucionado bug

- src/components/RegisterA/RegisterA.jsx
Se reparo parcialmente un bug de visualización de inputs RegisterA
> Register aupdate second

- src/components/InvestorBuy/InvestorBuy.jsx
- src/redux/actions/index.js
- src/redux/reducer/index.js
Por fin funciono la conexion con el back y ya trae las monedas.
> Conexion con el back ruta crypto

- src/components/CoinsInvestorBuy/CoinsInvestorBuy.jsx
- src/components/InvestorBuy/InvestorBuy.jsx
- src/redux/actions/index.js
- src/redux/reducer/index.js
Acabado el apartado de poder buscar monedas por nombre
> Buscador del apartado investor/buy listo

- src/redux/actions/index.js
Lista conexion de las monedas con el deploy
> Conexion con el deploy lista

- src/redux/actions/index.js
Se cambiaron las rutas de las actions a HEROKU
> ActionsHEROKU

- src/components/CoinsInvestorBuy/CoinsInvestorBuy.jsx
- src/components/DetailCoinsInvestorBuy/DetailCoinsInvestorBuy.jsx
- src/redux/actions/index.js
- src/redux/reducer/index.js
Esta listo el detalle de cada carta de las crypto
> Detail coins listas
